### ISSUE TITLE
cannot find -lopenxr_loader

### ISSUE THREAD

**Issue by ghost** [ILLIXR/Monado_OpenXR_Simple_Example#1]
When building with cmake 3.16.3 on Ubuntu 20.04, I get the above error. Though I am new to OpenXR and Monado, I am not sure if `libopenxr_loader` is part of what's built from latest Monado master.

**Comment by ilufang** [comment]
The openxr loader is provided by Khronos, and is required for any openxr app. It's available at  https://github.com/KhronosGroup/OpenXR-SDK

**Comment by ghost** [comment]
Please forgive my beginner questions. I just now built OpenXR-SDK in debug mode and ran `sudo make install`, where it indicated it copied libraries to their proper places. Your example project now builds, but when I run it, it says:

    ./openxr-example: error while loading shared libraries: libopenxr_loader.so.1: cannot open shared object file: No such file or directory

**Comment by JumboNomand** [comment]
Eh, sorry this project is not meant to be public right now. So we are still stablizing our code and finishing documentations including building instructions. We are targeting a stable release soon. Hopefully at the end this month. Please check back then.

To answer your question, it cannot find libopenxr_loader.so, which, in your case, should be under the default /user/local/lib directory. You need to include that path in your system environment variable.

Besides, in order to run openxr_simple_example with illixr, there are many other stuff you need to set up, including monado_integration, and a core illixr runtime (not shown in ILLIXR repo list yet).

**Comment by ghost** [comment]
Understood. Thank you. I will close this issue and revisit the project later.
